# Generated by Django 5.2.8 on 2026-03-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('move_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='warehouse.location')),
            ],
        ),
    ]
